const Runtime = Object.freeze({
    RUNTIME_SUPPORTING_PK_FK_CONSTRAINTS: 11,
    RUNTIME_SUPPORTING_NOT_NULL_CONSTRAINTS: 7,
    RUNTIME_SUPPORTING_MODIFYING_COLUMNS_WITHOUT_NEED_TO_RECREATE_TABLE: 11,
    MINIMUM_UNITY_CATALOG_SUPPORT_VERSION: 11,
});


module.exports = {
    Runtime
}
