module.exports = {
	DROP_STATEMENTS: [
		'DROP BLOOMFILTER',
		'DROP VIEW',
		'DROP TABLE',
		'DROP DATABASE',
		'DROP COLUMN',
		'DROP COLUMNS',
		"COMMENT '';",
		'IS NULL;',
		'DROP NOT NULL;',
		'DROP CONSTRAINT IF EXISTS',
	]
}
